messages:
  fly-enabled: '<gray>You can now fly!</gray>'
  fly-disabled: '<gray>You can no longer fly!</gray>'
  fly-enabled-other: '<gray>The player <white><name></white> can now fly!</gray>'
  fly-disabled-other: '<gray>The player <white><name></white> can no longer fly!</gray>'
  vanish-enabled: '<gray>You are now invisible!</gray>'
  vanish-disabled: '<gray>You are no longer invisible!</gray>'
  vanish-enabled-other: '<gray>The player <white><name></white> is now invisible!</gray>'
  vanish-disabled-other: '<gray>The player <white><name></white> is no longer invisible!</gray>'
  reload: '<gray>The plugin was reloaded!</gray>'
  player-not-found: '<red>The player <dark_red><name></dark_red> was not found!</red>'
  sender-has-to-be-a-player: '<red>The sender has to be a player!</red>'

crons:
  - interval: 300 # in seconds
    commands:
      - 'say <red>Hi</red> there'

events:
  new-joiner:
    - 'title %player% title {"text":"This is NO hacking"}'
